#!/usr/bin/env python3
"""
ETSI Evidence JSON Template Generator

Generates a pre-filled pre-evidence JSON that agents write into.
Eliminates the top L1 error categories: wrong enum values, missing fields, wrong filenames.

Usage:
  python generate_evidence_template.py <module_id> <workspace_path> [--retry N] [--only-clauses clauseId1,clauseId2]

Examples:
  python generate_evidence_template.py M1 D:/Auto-TEST/20260810_145858
  python generate_evidence_template.py M3 D:/Auto-TEST/20260810_145858 --retry 1
  python generate_evidence_template.py M3 D:/Auto-TEST/20260810_145858 --only-clauses 5.5-8
"""

import json
import os
import sys
import argparse
from datetime import datetime, timezone, timedelta


# ── Module definitions (synced with module-split.md) ──────────────────────

MODULES = {
    "M0": {
        "name": "ICS 逻辑验证",
        "output_stem": "ics_validation",
        "clauses": [],  # M0 is generated by main thread, not from this script
    },
    "M1": {
        "name": "攻击面与端口",
        "output_stem": "attack_surface",
        "clauses": [
            "5.5-2", "5.5-4", "5.5-5",
            "5.6-1", "5.6-2", "5.6-3", "5.6-4", "5.6-5",
            "5.6-6", "5.6-7", "5.6-8", "5.6-9",
        ],
    },
    "M2": {
        "name": "认证与口令",
        "output_stem": "auth_password",
        "clauses": [
            "5.1-1", "5.1-2", "5.1-3", "5.1-4", "5.1-5",
        ],
    },
    "M3": {
        "name": "通信加密",
        "output_stem": "comm_crypto",
        "clauses": [
            "5.5-1", "5.5-3", "5.5-6", "5.5-7", "5.5-8",
            "5.8-1", "5.8-2",
        ],
    },
    "M4": {
        "name": "更新与完整性",
        "output_stem": "update_integrity",
        "clauses": [
            "5.3-1", "5.3-2", "5.3-3", "5.3-4", "5.3-5",
            "5.3-6A", "5.3-6B", "5.3-7", "5.3-8", "5.3-9",
            "5.3-10", "5.3-11", "5.3-12", "5.3-13", "5.3-14",
            "5.3-15", "5.3-16",
            "5.4-1", "5.4-2", "5.4-3", "5.4-4",
            "5.7-1", "5.7-2",
        ],
    },
    "M5": {
        "name": "输入验证与数据保护",
        "output_stem": "input_dataprotection",
        "clauses": [
            "5.2-1", "5.2-2", "5.2-3",
            "5.8-3",
            "5.9-1", "5.9-2", "5.9-3",
            "5.10",
            "5.11-1", "5.11-2", "5.11-3", "5.11-4",
            "5.12-1", "5.12-2", "5.12-3",
            "5.13-1",
            "6-1", "6-2", "6-3", "6-4", "6-5",
            "6-6", "6-7", "6-8",
        ],
    },
}

# ── Provision text lookup (from EN 303 645) ──────────────────────────────

PROVISION_TEXTS = {
    "5.1-1": "Where passwords are used, all consumer IoT device passwords shall be unique per device or user-defined.",
    "5.1-2": "Pre-installed unique per device passwords shall be generated with a mechanism that reduces the risk of automated attacks.",
    "5.1-3": "Authentication mechanisms shall use best practice cryptography, appropriate to the properties of the technology, risk and usage.",
    "5.1-4": "Where a user can authenticate against a device, they shall be able to change any secret authentication value.",
    "5.1-5": "The device shall have a mechanism to protect against brute-force authentication attempts.",
    "5.2-1": "The manufacturer shall make a vulnerability disclosure policy publicly available.",
    "5.2-2": "Disclosed vulnerabilities should be acted on in a timely manner.",
    "5.2-3": "Manufacturers should continually monitor for and rectify security vulnerabilities within products and services.",
    "5.3-1": "All software components that are not immutable should be securely updateable.",
    "5.3-2": "The device shall have a secure update mechanism unless resource-constrained.",
    "5.3-3": "Updates shall be simple for the user to apply.",
    "5.3-4": "Automatic update mechanisms should be used where appropriate.",
    "5.3-5": "The device should check for updates regularly.",
    "5.3-6A": "The device should notify the user when an update is available.",
    "5.3-6B": "The device should provide a means for the user to initiate an update check.",
    "5.3-7": "Update mechanisms shall use best practice cryptography.",
    "5.3-8": "Security updates shall be timely.",
    "5.3-9": "The device shall verify the authenticity and integrity of software updates.",
    "5.3-10": "Updates shall be delivered through a trusted channel.",
    "5.3-11": "For constrained devices that cannot support updates, upgrade planning should be documented.",
    "5.3-12": "The device should provide a means to notify the user of an impending update that will disrupt its functioning.",
    "5.3-13": "The manufacturer shall publish the defined support period for the device.",
    "5.3-14": "The manufacturer shall publish a vulnerability disclosure policy.",
    "5.3-15": "For constrained devices not supporting automatic updates, upgrade paths should be defined.",
    "5.3-16": "The model designation of the device shall be clearly identifiable.",
    "5.4-1": "Hardware security mechanisms should be used to protect the integrity of the device.",
    "5.4-2": "The device should not rely on a single hardware security mechanism.",
    "5.4-3": "Secure boot or secure initialisation should be implemented.",
    "5.4-4": "Critical security parameters shall be unique per device.",
    "5.5-1": "The device shall use best practice cryptography to secure communication.",
    "5.5-2": "The device shall only use well-known and publicly reviewed network protocols.",
    "5.5-3": "Cryptographic algorithms and primitives should be updateable.",
    "5.5-4": "Access to device functionality via a network interface shall only be possible after authentication.",
    "5.5-5": "The device shall implement protections against brute-force access via network interfaces.",
    "5.5-6": "Communication security mechanisms should be applied to all data in transit.",
    "5.5-7": "Critical security parameters should be encrypted in transit.",
    "5.5-8": "The manufacturer shall follow secure development processes for software.",
    "5.6-1": "All network and logical interfaces shall be documented in IXIT 15-Intf.",
    "5.6-2": "The device shall not unnecessarily expose security-relevant information via network interfaces.",
    "5.6-3": "Wireless network interfaces should be disabled by default.",
    "5.6-4": "Hardware debug interfaces shall be disabled by default or accessible only after authentication.",
    "5.6-5": "Only necessary services shall be enabled by default.",
    "5.6-6": "The principle of least privilege shall be applied to software components.",
    "5.6-7": "The device shall enforce privilege separation.",
    "5.6-8": "Access control mechanisms shall be implemented to prevent unauthorised access.",
    "5.6-9": "Software shall be developed following secure development practices.",
    "5.7-1": "The device shall verify the integrity of stored security-relevant data.",
    "5.7-2": "If the integrity check fails, the device should alert the user.",
    "5.8-1": "Personal data in transit shall be protected against unauthorised access.",
    "5.8-2": "Sensitive personal data shall be encrypted in transit using best practice cryptography.",
    "5.8-3": "The manufacturer shall provide a means for the user to access, rectify, and erase personal data.",
    "5.9-1": "The device shall remain operational and locally functional when the network is unavailable.",
    "5.9-2": "The device should resume normal operation after a loss of network connectivity.",
    "5.9-3": "The device should reconnect in an orderly fashion after a network outage.",
    "5.10": "Telemetry data collection shall be disclosed to the user.",
    "5.11-1": "The consumer shall be able to delete personal data from the device.",
    "5.11-2": "Personal data in associated services shall be deletable.",
    "5.11-3": "Clear instructions shall be provided on how to decommission the device.",
    "5.11-4": "The consumer shall be able to export personal data from the device.",
    "5.12-1": "The user shall be able to make informed decisions about data collection and processing.",
    "5.12-2": "Installation and maintenance instructions shall be provided.",
    "5.12-3": "The device shall provide guidance on secure configuration.",
    "5.13-1": "The device shall validate input from all sources.",
    "6-1": "The manufacturer shall provide clear and transparent information about personal data processing.",
    "6-2": "The consumer shall give explicit consent for personal data processing.",
    "6-3": "The consumer shall be able to withdraw consent for personal data processing.",
    "6-4": "Personal data portability shall be supported.",
    "6-5": "Data retention periods shall be published.",
    "6-6": "Data stored and processed shall be limited to that which is necessary, and deleted once no longer necessary.",
    "6-7": "When data collection is solely to compute an aggregate result, the data collected should be the minimum required.",
    "6-8": "Data anonymization technologies should be used to protect privacy.",
}

# ── ICS mapping ─────────────────────────────────────────────────────────

def _clause_id_to_section(clause_id: str) -> str:
    """Extract section number from clause ID: '5.6-1' -> '5.6', '6-1' -> '6'"""
    parts = clause_id.split("-")
    if len(parts) >= 2:
        # Return the numeric prefix: 5.6-1 -> 5.6, 6-1 -> 6, 5.3-6A -> 5.3
        return parts[0]
    return clause_id


def _build_ics_lookup(ixit_json_path: str) -> dict:
    """
    Build a lookup dict from clause_id -> {icsStatus, icsSupport, provisionText, icsDetail}
    using both the ICS array and IXIT tables in ixit.json.
    """
    if not os.path.exists(ixit_json_path):
        return {}

    with open(ixit_json_path, encoding="utf-8") as f:
        ixit = json.load(f)

    lookup = {}
    ics_list = ixit.get("ics", [])

    # Build by section: clause_id -> best match
    for entry in ics_list:
        section = entry.get("clause", "")
        provision_text = entry.get("provision_text", "")
        applicability = entry.get("applicability", "")
        status = entry.get("status", "")

        # Derive icsSupport from ICS fields
        if applicability in ("Not applicable", "not applicable"):
            ics_support = "N/A"
        elif status.startswith("M"):
            ics_support = "Y"
        elif status.startswith("R"):
            ics_support = "Y"
        else:
            ics_support = "Y"  # Default: assume support if not explicitly N/A

        # Store by section for later clause-level matching
        lookup[section] = {
            "icsStatus": status,
            "icsSupport": ics_support,
            "provisionText": provision_text,
            "icsDetail": "",
        }

    return lookup


# ── Template generation ──────────────────────────────────────────────────

def generate_template(
    module_id: str,
    workspace_path: str,
    retry_count: int = 0,
    only_clauses: list | None = None,
) -> dict:
    """Generate a pre-filled evidence JSON template."""

    if module_id not in MODULES:
        raise ValueError(f"Unknown module_id: {module_id}. Valid: {list(MODULES.keys())}")

    mod = MODULES[module_id]
    clause_ids = only_clauses if only_clauses else mod["clauses"]

    # Resolve paths
    ixit_json_path = os.path.join(workspace_path, "ixit.json")
    dut_ip = _detect_dut_ip(workspace_path)

    # Build ICS lookup
    ics_lookup = _build_ics_lookup(ixit_json_path)

    # Now in Beijing timezone
    now = datetime.now(timezone(timedelta(hours=8))).isoformat()

    # Build clauses
    clauses = []
    for cid in clause_ids:
        section = _clause_id_to_section(cid)
        ics_info = ics_lookup.get(section, {})

        # Prefer own PROVISION_TEXTS, fall back to ICS text
        provision_text = PROVISION_TEXTS.get(cid) or ics_info.get("provisionText", "")
        # Truncate provision text to 1 sentence
        if provision_text and len(provision_text) > 200:
            provision_text = provision_text[:197] + "..."

        clause = {
            "clauseId": cid,
            "provisionText": provision_text,
            "icsStatus": ics_info.get("icsStatus", ""),
            "icsSupport": ics_info.get("icsSupport", "Y"),
            "icsDetail": ics_info.get("icsDetail", ""),
            "verdict": "INCONCLUSIVE",       # Placeholder — agent MUST overwrite
            "reason": "[AGENT: fill in]",     # Placeholder — agent MUST overwrite
            "expectedBehavior": None,
            "actualBehavior": None,
            "evidence": [],
            "ixitReferences": [],
            "tags": [],
            "warnings": [],
            "manualSteps": None,
            "retryHistory": [],
        }
        clauses.append(clause)

    # Build selfCheck
    self_check = {
        "totalExpected": len(clause_ids),
        "actualInJson": len(clauses),
        "missingClauses": [],
        "uncertainClauses": [c["clauseId"] for c in clauses],
        "failCount": 0,
        "failClauses": [],
        "pendingManual": 0,
        "pendingManualClauses": [],
        "icsNAClauses": [c["clauseId"] for c in clauses if c["icsSupport"] == "N/A"],
        "hasErrors": False,
    }

    # Build executionTrace skeleton
    execution_trace = {
        "startedAt": now,
        "completedAt": None,
        "totalRounds": 0,
        "selfReportedBudgetUsed": 0,
        "steps": [],
        "warnings": [],
    }

    template = {
        "meta": {
            "moduleId": module_id,
            "moduleName": mod["name"],
            "dutIp": dut_ip,
            "ixitJsonPath": ixit_json_path,
            "generatedAt": now,
            "clauseCount": len(clause_ids),
            "retryCount": retry_count,
            "status": "pending_audit",
        },
        "executionTrace": execution_trace,
        "clauses": clauses,
        "selfCheck": self_check,
    }

    return template


def _detect_dut_ip(workspace_path: str) -> str:
    """Try to detect DUT IP from nmap_tcp.txt in workspace."""
    nmap_path = os.path.join(workspace_path, "nmap_tcp.txt")
    if os.path.exists(nmap_path):
        import re
        with open(nmap_path, encoding="utf-8", errors="ignore") as f:
            for line in f:
                m = re.search(r"Nmap scan report for (\d+\.\d+\.\d+\.\d+)", line)
                if m:
                    return m.group(1)
    return ""


def get_output_filename(module_id: str, retry_count: int = 0) -> str:
    """Generate the correct filename per module-split.md naming convention."""
    if module_id not in MODULES:
        raise ValueError(f"Unknown module_id: {module_id}")
    stem = MODULES[module_id]["output_stem"]
    return f"pre-evidence_{module_id}_{stem}_x{retry_count}.json"


# ── CLI ──────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate pre-filled ETSI evidence JSON template"
    )
    parser.add_argument("module_id", help="Module ID: M1-M5")
    parser.add_argument("workspace", help="Workspace directory path")
    parser.add_argument(
        "--retry", type=int, default=0,
        help="Retry count (0=first attempt, 1-2=retry)"
    )
    parser.add_argument(
        "--only-clauses", type=str, default=None,
        help="Comma-separated clause IDs to include (for supplement/retry)"
    )

    args = parser.parse_args()

    # Validate module_id
    if args.module_id not in MODULES or args.module_id == "M0":
        print(f"ERROR: module_id must be one of M1,M2,M3,M4,M5 (got: {args.module_id})")
        sys.exit(1)

    # Parse only-clauses
    only = None
    if args.only_clauses:
        only = [c.strip() for c in args.only_clauses.split(",")]

    # Generate
    template = generate_template(
        module_id=args.module_id,
        workspace_path=args.workspace,
        retry_count=args.retry,
        only_clauses=only,
    )

    # Determine output path
    filename = get_output_filename(args.module_id, args.retry)
    output_path = os.path.join(args.workspace, filename)

    # Write atomically: .tmp -> validate -> rename
    tmp_path = output_path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(template, f, indent=2, ensure_ascii=False)

    # Validate
    with open(tmp_path, encoding="utf-8") as f:
        json.load(f)

    # If final file already exists, remove it (it's stale)
    if os.path.exists(output_path):
        os.remove(output_path)
    os.rename(tmp_path, output_path)

    # Quick self-check summary
    sc = template["selfCheck"]
    print(f"[OK] Template generated: {output_path}")
    print(f"     Module: {template['meta']['moduleName']} ({args.module_id})")
    print(f"     Clauses: {sc['totalExpected']} | ICS N/A: {len(sc['icsNAClauses'])}")
    print(f"     DUT IP: {template['meta']['dutIp'] or '(not detected)'}")
    print(f"     Retry: {args.retry}")
    print(f"     All enum values pre-filled — agent fills verdict/reason/evidence only.")


if __name__ == "__main__":
    main()
